spring:
  application:
    name: "Gerenciador de pedidos"
  datasource:
    url: jdbc:mysql://localhost:3306/gerenciador
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
  servlet:
    context-path: /gerenciador-pedidos

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
